# Generated by Django 4.2.16 on 2025-05-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annual_salary',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='연봉'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_assets',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='현재 가진 금액'),
        ),
    ]
