# Generated by Django 4.2.16 on 2025-05-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_deposit_products',
            field=models.ManyToManyField(related_name='subscribed_users', through='financials.UserDeposit', to='financials.depositproduct'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_saving_products',
            field=models.ManyToManyField(related_name='subscribed_users', through='financials.UserSaving', to='financials.savingproduct'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
