# Generated by Django 4.2.16 on 2025-05-23 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(blank=True, max_length=6, null=True)),
                ('fin_prdt_cd', models.CharField(blank=True, max_length=50, null=True)),
                ('fin_co_no', models.CharField(blank=True, max_length=50, null=True)),
                ('kor_co_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('fin_prdt_nm', models.CharField(blank=True, max_length=150, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('join_deny', models.SmallIntegerField(blank=True, null=True)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.BigIntegerField(blank=True, null=True)),
                ('interest_user', models.ManyToManyField(blank=True, related_name='interesting_deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(blank=True, max_length=6, null=True)),
                ('fin_prdt_cd', models.CharField(blank=True, max_length=50, null=True)),
                ('fin_co_no', models.CharField(blank=True, max_length=50, null=True)),
                ('kor_co_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('fin_prdt_nm', models.CharField(blank=True, max_length=150, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('join_deny', models.SmallIntegerField(blank=True, null=True)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.BigIntegerField(blank=True, null=True)),
                ('interest_user', models.ManyToManyField(blank=True, related_name='interesting_savings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(blank=True, max_length=100, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('rsrv_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('save_trm', models.IntegerField(blank=True, null=True)),
                ('intr_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intr_rate2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saving_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='financials.savingproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(blank=True, max_length=100, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('save_trm', models.IntegerField(blank=True, null=True)),
                ('intr_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intr_rate2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('deposit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='financials.depositproduct')),
            ],
        ),
        migrations.CreateModel(
            name='UserSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateField(auto_now_add=True)),
                ('maturity_at', models.DateField(blank=True, null=True)),
                ('principal', models.BigIntegerField(default=0)),
                ('applied_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saving_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.savingproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'saving_product', 'signed_at')},
            },
        ),
        migrations.CreateModel(
            name='UserDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateField(auto_now_add=True)),
                ('maturity_at', models.DateField(blank=True, null=True)),
                ('principal', models.BigIntegerField(default=0)),
                ('applied_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('deposit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.depositproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'deposit_product', 'signed_at')},
            },
        ),
    ]
